version: '3.3'
services:


  server:
    container_name: Server
    build:
      context: ./src/server/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      API_KEY: /run/secrets/api_key
      PORT: 443
    volumes:
      - ./src/server:/app
    secrets:
      - api_key

secrets:
  api_key:
    file: ./assets/secrets/api_key

